name: ibm.spectrum_virtualize Ansible CI

on:
  push:
  pull_request:
  schedule:
    - cron: '25 10 * * *'

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible }} on spectrum_virtualize
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - stable-2.9
          - stable-2.10
          - stable-2.11
          - stable-2.12
          
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install ansible (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Make directory for ansible-test 
        run: |
          pwd
          mkdir -p ansible_collections/ibm/spectrum_virtualize
          rsync -av . ansible_collections/ibm/spectrum_virtualize --exclude ansible_collections/ibm/spectrum_virtualize
      - name: Run sanity tests spectrum_virtualize
        run: ansible-test sanity -v --color --docker --coverage --python 3.8
        working-directory: ./ansible_collections/ibm/spectrum_virtualize

  units:
    name: Units (${{ matrix.ansible }} on spectrum_virtualize
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.9
          - stable-2.10
          - stable-2.11
          #- stable-2.12
        python:
          #- '2.6'
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
        exclude:
          # Because ansible-test doesn't support Python 3.9 for Ansible 2.9
          # and Python 3.10 is supported in 2.12 or later.
          - ansible: stable-2.9
            python: '3.9'
          - ansible: stable-2.9
            python: '3.10'
          - ansible: stable-2.10
            python: '3.10'
          - ansible: stable-2.11
            python: '3.10'
            
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install ansible (${{ matrix.ansible }})
        run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

      - name: Make directory for ansible-test 
        run: |
          pwd
          mkdir -p ansible_collections/ibm/spectrum_virtualize
          rsync -av . ansible_collections/ibm/spectrum_virtualize --exclude ansible_collections/ibm/spectrum_virtualize
      - name: Run unit test cases
        run: ansible-test units -v --color --docker --coverage
        working-directory: ./ansible_collections/ibm/spectrum_virtualize
